name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11
        ports:
          - 3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
          MYSQL_ALLOW_EMPTY_PASSWORD: false

      redis:
        image: redis
        ports:
          - 6379/tcp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug
          extensions: mysql, redis

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup Environment File
        run: cp .env.testing .env

      - name: Clear Caches
        run: |
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear

      - name: Wait for services
        run: |
          echo "Waiting for services to be ready..."
          sleep 10

      - name: Run Migration
        run: php artisan migrate --force -v
        env:
          APP_KEY: 'base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
          DB_DATABASE: testing
          DB_PORT: ${{ job.services.mariadb.ports['3306'] }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}

      - name: Tests
        run: ./vendor/bin/pest
        env:
          APP_KEY: 'base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
          DB_DATABASE: testing
          DB_PORT: ${{ job.services.mariadb.ports['3306'] }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
